### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by jencheng** [hrs/primer-finder#17]
I take back about what I said with the blue vs red coloring.

I think it would be clearer if you do:

target  5'        GATTACA       3'
primer 5'           ATTA            3'

**Comment by hrs** [comment]
@jencheng Nudge, nudge.

**Comment by jencheng** [comment]
I think it looks nicer w/out blue if we have `target` and `primer`, but we can leave it if you want

**Comment by hrs** [comment]
Nope, I'm fine with removing it. Fixed in https://github.com/hrs/primer-finder/commit/4fc93e1e9d383d672aae43bacd7844a314650d3a, should be deploying to production now. Give it a shot and lemme know if you want it changed.

**Comment by hrs** [comment]
@jencheng: Ping!

**Comment by hrs** [comment]
I'm gonna just mark this as fixed. Let me know if it should be reopened.
