### ISSUE TITLE
Set up gemnasium

### ISSUE THREAD

**Issue by albertyw** [hrs/primer-finder#25]
If you're worried about gems going out of date (and from your last commit, you are), then you may want to monitor your gems.  (you can add another badge to your readme)

**Comment by hrs** [comment]
I'm not too worried about it; Travis is running [bundler-audit](https://github.com/rubysec/bundler-audit), which does the job.

For example, see [the failure](https://travis-ci.org/hrs/primer-finder/builds/107616160) that led to [that last commit](https://github.com/hrs/primer-finder/commit/b770c7e37f254e0e3086022a7a8659f8c9f5a661).
